Repository traefik/yaegi, pull requests merged in 2019-08, with the labels that each got.

#319 chore: add goexports to the archive.
  .gitignore
  .goreleaser.yml
Labels: area/infrastructure, enhancement, status/3-needs-merge

#330 feature: locate origin of CFG panic in input source
  interp/cfg.go
Labels: area/core, enhancement

#333 doc: add a contributing guide
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  README.md
Labels: area/doc, enhancement

#329 fix: do not skip AST errors when not in REPL mode
  _test/bad0.go
  interp/ast.go
  interp/build.go
  interp/build_test.go
  interp/interp_consistent_test.go
Labels: area/core, area/repl, bug

#335 fix: iterate on global type analyis when necessary
  _test/method21.go
  _test/method22.go
  _test/method23.go
  _test/struct12.go
  _test/struct15.go
  _test/struct19.go
  _test/type12.go
  _test/type13.go
  _test/type14.go
  interp/gta.go
  interp/interp.go
  interp/src.go
Labels: area/core, bug

#336 fix: improve handling of global declarations, possibly out of order
  _test/a32.go
  _test/composite0.go
  _test/composite1.go
  _test/composite2.go
  _test/method24.go
  _test/select0.go
  _test/struct24.go
  _test/struct25.go
  _test/time8.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/run.go
  interp/scope.go
  interp/type.go
Labels: area/core, bug

#339 fix: assign a function value to a pre-declared variable
  _test/assign9.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge
