Repository traefik/yaegi, pull requests merged in 2019-09, with the labels that each got.

#344 fix: improve handling of out of order declarations
  _test/fun6.go
  _test/method25.go
  _test/method26.go
  _test/struct26.go
  _test/struct27.go
  _test/struct28.go
  interp/cfg.go
  interp/gta.go
  interp/run.go
  interp/scope.go
  interp/type.go
Labels: area/core, bug

#349 fix: correct computation of type when dereference a binary object
  _test/ptr7.go
  interp/cfg.go
Labels: area/core, bug

#347 fix: avoid collision between package names and function args
  _test/fun7.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#350 fix: reuse rather than re-import an already imported source package
  _test/foo/bar.go
  _test/foo/bir.go
  _test/foo/boo/boo.go
  _test/import3.go
  _test/import4.go
  _test/import5.go
  interp/gta.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/interp_file_test.go
  interp/src.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#353 fix: implement variadic using a type category to avoid corruption
  _test/variadic4.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#355 fix: correct resolve of type and symbols from imported source package
  interp/cfg.go
  interp/interp.go
Labels: area/core, bug, status/3-needs-merge

#356 fix: add support for out of order declarations of empty global variables
  _test/fun8.go
  interp/gta.go
Labels: area/core, bug, status/3-needs-merge

#366 feature: additional binary packages in stdlib
  cmd/goexports/goexports.go
  stdlib/go1_11_debug_dwarf.go
  stdlib/go1_11_debug_elf.go
  stdlib/go1_11_debug_gosym.go
  stdlib/go1_11_debug_macho.go
  stdlib/go1_11_debug_pe.go
  stdlib/go1_11_debug_plan9obj.go
  stdlib/go1_11_net_http_pprof.go
  stdlib/go1_11_runtime_pprof.go
  stdlib/go1_11_runtime_trace.go
  stdlib/go1_12_debug_dwarf.go
  stdlib/go1_12_debug_elf.go
  stdlib/go1_12_debug_gosym.go
  stdlib/go1_12_debug_macho.go
  stdlib/go1_12_debug_pe.go
  stdlib/go1_12_debug_plan9obj.go
  stdlib/go1_12_net_http_pprof.go
  stdlib/go1_12_runtime_pprof.go
  stdlib/go1_12_runtime_trace.go
  stdlib/go1_13_crypto_ed25519.go
  stdlib/go1_13_debug_dwarf.go
  stdlib/go1_13_debug_elf.go
  stdlib/go1_13_debug_gosym.go
  stdlib/go1_13_debug_macho.go
  stdlib/go1_13_debug_pe.go
  stdlib/go1_13_debug_plan9obj.go
  stdlib/go1_13_net_http_pprof.go
  stdlib/go1_13_runtime_pprof.go
  stdlib/go1_13_runtime_trace.go
  stdlib/stdlib.go
Labels: area/core, enhancement

#360 fix: global variable init from selector expression
  _test/var8.go
  interp/cfg.go
  interp/gta.go
  interp/interp.go
  interp/scope.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#362 fix: conversion of type to reflect.Type avoids recursive loop
  _test/recurse0.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#367 chore: build only master branch.
  .travis.yml
Labels: area/infrastructure, enhancement, status/3-needs-merge

#358 fix: init global var from builtin
  _test/map18.go
  _test/var7.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#364 fix: support defining recursive interface types
  _test/interface10.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#365 feature: detect import cycle
  _test/c1/c1.go
  _test/c2/c2.go
  _test/import6.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/src.go
Labels: area/core, enhancement, status/3-needs-merge

#369 fix: support array operations on array pointers
  _test/copy1.go
  _test/ptr_array0.go
  _test/ptr_array1.go
  _test/ptr_array2.go
  _test/ptr_array3.go
  interp/cfg.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#370 fix: shift operator inherits its type from first arg only
  _test/shift1.go
  _test/shift2.go
  interp/cfg.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#373 chore: allow to build tags
  .travis.yml
Labels: area/infrastructure, status/3-needs-merge

#374 fix: binary method lookup works for struct field pointer receiver
  _test/method27.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#376 doc: README, supported go versions: 1.12 and 1.13
  README.md
Labels: area/doc, enhancement, status/3-needs-merge

#375 fix: support variadic parameters on methods
  _test/variadic5.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#377 fix: range over string iterates on runes instead of bytes
  _test/for6.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#379 fix: handle forward declaration of alias type
  _test/alias1.go
  interp/gta.go
Labels: area/core, bug, status/3-needs-merge

#385 test: ensure hour-aligned timezone
  _test/time5.go
Labels: bug, status/3-needs-merge

#382 interp: don't panic for undefined types
  interp/cfg.go
  interp/interp_eval_test.go
Labels: area/core, bug, status/3-needs-merge

#383 fix: correct automatic type conversion for untyped constants
  _test/shift3.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#381 fix: correct handling of types alias of interfaces
  _test/interface11.go
  example/pkg/pkg_test.go
  interp/cfg.go
  interp/gta.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#388 fix: handle type declaration inside function
  _test/fun9.go
  interp/cfg.go
  interp/gta.go
Labels: area/core, bug, status/3-needs-merge

#391 fix: goexports to convert value type only for untyped constants
  _test/time9.go
  cmd/goexports/goexports.go
  stdlib/go1_11_debug_elf.go
  stdlib/go1_11_debug_macho.go
  stdlib/go1_11_os.go
  stdlib/go1_11_time.go
  stdlib/go1_12_debug_elf.go
  stdlib/go1_12_debug_macho.go
  stdlib/go1_12_os.go
  stdlib/go1_12_time.go
  stdlib/go1_13_debug_elf.go
  stdlib/go1_13_debug_macho.go
  stdlib/go1_13_os.go
  stdlib/go1_13_time.go
  stdlib/syscall/go1_11_syscall_windows_386.go
  stdlib/syscall/go1_11_syscall_windows_amd64.go
  stdlib/syscall/go1_12_syscall_netbsd_arm64.go
  stdlib/syscall/go1_12_syscall_openbsd_arm64.go
  stdlib/syscall/go1_12_syscall_windows_386.go
  stdlib/syscall/go1_12_syscall_windows_amd64.go
  stdlib/syscall/go1_12_syscall_windows_arm.go
  stdlib/syscall/go1_13_syscall_windows_386.go
  stdlib/syscall/go1_13_syscall_windows_amd64.go
  stdlib/syscall/go1_13_syscall_windows_arm.go
Labels: area/goexports, bug, status/3-needs-merge

#392 interp: fix range expression handling
  _test/range0.go
  _test/range1.go
  _test/range2.go
  interp/cfg.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#395 interp: fix array size assignment type inference
  _test/a33.go
  _test/a34.go
  _test/a35.go
  _test/a36.go
  _test/a37.go
  _test/a38.go
  _test/a39.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge
