Repository traefik/yaegi, pull requests merged in 2019-07, with the labels that each got.

#250 Fix installation instructions
  README.md
Labels: area/doc, bug

#255 fix: blank identifier cause panic
  _test/assign8.go
  interp/cfg.go
Labels: bug

#256 doc: improve documentation.
  README.md
Labels: area/doc, enhancement, status/3-needs-merge

#263 feat: support yaegi in go playground
  .travis.yml
  Makefile
  interp/interp.go
Labels: area/core, enhancement, status/3-needs-merge

#267 fix: exclude syslog for windows, nacl, and plan9.
  cmd/goexports/goexports.go
  stdlib/go1_11_log_syslog.go
  stdlib/go1_12_log_syslog.go
Labels: area/core, bug, status/3-needs-merge

#279 doc: add playground examples.
  README.md
Labels: area/doc, enhancement, status/3-needs-merge

#282 doc: Fixes the title and other formattings
  README.md
Labels: area/doc, enhancement, status/3-needs-merge

#284 doc: first attempt to document goexports command
  cmd/goexports/goexports.go
Labels: area/goexports, enhancement, status/3-needs-merge

#291 fix: correct assign to binary interface value
  _test/interface9.go
  interp/run.go
Labels: area/core, bug

#295 doc: add a Limitations section in README
  README.md
Labels: area/doc, enhancement, status/3-needs-merge

#299 doc: add community badge.
  README.md
Labels: area/doc, enhancement, status/3-needs-merge

#305 goexports: allow to generate mapping for devel, beta, and rc.
  cmd/goexports/goexports.go
Labels: area/goexports, enhancement, status/3-needs-merge

#313 fix: support 'range' with no index and value assigned
  _test/a30.go
  _test/a31.go
  interp/ast.go
Labels: area/core, bug, status/3-needs-merge

#306 interp/build: improve Go version handling.
  .golangci.toml
  interp/build.go
  interp/build_test.go
  stdlib/stdlib.go
  stdlib/syscall/syscall.go
  stdlib/unsafe/unsafe.go
Labels: area/core, enhancement, status/3-needs-merge

#318 interp/build: support custom build constraints.
  interp/ast.go
  interp/build.go
  interp/build_test.go
  interp/interp.go
  interp/src.go
Labels: area/core, enhancement, status/3-needs-merge
