Repository traefik/yaegi, pull requests merged in 2019-10, with the labels that each got.

#393 interp: fix map range handling
  .travis.yml
  _test/range3.go
  _test/range4.go
  _test/range5.go
  _test/range6.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#397 fix: compute type of slice expression globally
  _test/var9.go
  interp/cfg.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#400 fix: generate closures for literal functions in CFG
  _test/closure8.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#404 interp: use io.Reader and io.Writer for REPL parameters
  interp/interp.go
Labels: area/api, area/repl, enhancement, status/3-needs-merge

#399 feature: rename exported func Repl into REPL
  .golangci.toml
  cmd/yaegi/yaegi.go
  interp/interp.go
Labels: area/api, enhancement, status/3-needs-merge

#405 chore: update linter to support go1.13
  .golangci.toml
  example/pkg/pkg_test.go
  internal/genop/genop.go
  interp/cfg.go
  interp/op.go
  interp/run.go
Labels: area/infrastructure, enhancement, status/3-needs-merge

#406 feature: add support for custom build tags
  _test/ct/ct1.go
  _test/ct/ct2.go
  _test/ct/ct3.go
  _test/tag0.go
  cmd/yaegi/yaegi.go
  interp/ast.go
  interp/build.go
  interp/build_test.go
  interp/doc.go
  interp/interp_consistent_test.go
  interp/src.go
Labels: area/core, enhancement, status/3-needs-merge

#417 fix: do not hide receiver type for method with anonymous receiver
  _test/method28.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#420 feat: update syscall for go1.12.12
  stdlib/syscall/go1_12_syscall_aix_ppc64.go
Labels: enhancement, status/3-needs-merge

#411 fix: assign untyped value to typed var may require type conversion
  _test/assign10.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#410 fix: assign binary func to func type var
  _test/time10.go
  cmd/goexports/goexports.go
  interp/doc.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#414 fix: goexports performs correct conversion on float32 constants
  _test/math1.go
  cmd/goexports/goexports.go
  stdlib/go1_12_math.go
  stdlib/go1_13_math.go
Labels: area/goexports, bug, status/3-needs-merge

#402 interp: add eval cancelation by semaphore
  Makefile
  cmd/yaegi/yaegi_test.go
  interp/ast.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/run.go
  interp/scope.go
  interp/src.go
  interp/value.go
Labels: area/api, area/core, area/repl, enhancement

#418 fix: improve handling of untyped complex numbers
  _test/complex1.go
  _test/complex2.go
  _test/complex3.go
  internal/genop/genop.go
  interp/cfg.go
  interp/op.go
  interp/run.go
  interp/type.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#429 doc: fix spelling
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: area/doc, bug, status/3-needs-merge

#432 fix: automatic conversion of untyped literal float to int
  _test/op4.go
  interp/ast.go
  interp/cfg.go
  interp/interp_eval_test.go
Labels: area/core, bug, status/3-needs-merge
