Repository traefik/yaegi, pull requests merged in 2020-10, with the labels that each got.

#881 interp: apply integer division when appropriate
  _test/const17.go
  cmd/yaegi/yaegi.go
  internal/cmd/genop/genop.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/op.go
  interp/typecheck.go
Labels: area/core, area/repl, bug, status/3-needs-merge

#876 fix: compute array type size from constant expression
  _test/a43.go
  interp/gta.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#885 interp: fix implicit type for bin composite lit case
  _test/binstruct_slice0.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#892 interp: support implicit-type slice of pointers of struct composite literal
  _test/binstruct_ptr_map0.go
  _test/binstruct_ptr_slice0.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#891 fix: allow yaegi command to interpret itself
  README.md
  cmd/yaegi/run.go
  cmd/yaegi/yaegi.go
  interp/hooks.go
  interp/interp.go
  interp/run.go
  interp/src.go
  interp/type.go
Labels: area/core, area/doc, area/repl, bug, status/3-needs-merge

#895 fix: perform constant type conversion when required
  _test/const18.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#894 fix: correct handling of select comm clause with empty body
  _test/select14.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#899 fix: behavior of select and time ticker
  Makefile
  _test/select14.go
  _test/select15.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#898 feature: provide a version sub-command
  Makefile
  cmd/yaegi/help.go
  cmd/yaegi/yaegi.go
Labels: area/infrastructure, area/repl, enhancement, status/3-needs-merge

#900 fix: detect a wrong number of arguments at return
  _test/fun23.go
  cmd/yaegi/run.go
  cmd/yaegi/yaegi.go
  interp/cfg.go
  interp/interp_consistent_test.go
Labels: area/core, bug, status/3-needs-merge

#902 interp: make Symbols method take into account type objects too
  interp/interp.go
Labels: area/core, enhancement, status/3-needs-merge

#903 interp: API change for Symbols method
  cmd/yaegi/test.go
  interp/interp.go
Labels: area/api, area/core, enhancement, status/3-needs-merge

#904 feature: use environment in addition to flags to control test options
  cmd/yaegi/test.go
Labels: area/cli, area/test, enhancement, status/3-needs-merge

#905 feature: expose extract package, previously internal
  cmd/yaegi/extract.go
  extract/extract.go
  extract/extract_test.go
  extract/testdata/1/src/guthib.com/bar/main.go
  extract/testdata/1/src/guthib.com/baz/baz.go
  extract/testdata/1/src/guthib.com/baz/go.mod
  extract/testdata/2/src/guthib.com/bar/main.go
  extract/testdata/2/src/guthib.com/baz/baz.go
  extract/testdata/3/src/guthib.com/bar/main.go
  extract/testdata/3/src/guthib.com/baz/baz.go
  extract/testdata/3/src/guthib.com/baz/go.mod
  extract/testdata/4/src/guthib.com/bar/main.go
  extract/testdata/4/src/guthib.com/bar/vendor/guthib.com/baz/baz.go
  extract/testdata/4/src/guthib.com/bar/vendor/guthib.com/baz/go.mod
  extract/testdata/5/src/guthib.com/bar/main.go
  extract/testdata/5/src/guthib.com/bar/vendor/guthib.com/baz/baz.go
  generate.go
  internal/cmd/extract/extract.go
Labels: area/api, enhancement, status/3-needs-merge

#786 chore: add homebrew-tap recipe
  .goreleaser.yml
Labels: area/infrastructure, enhancement, status/3-needs-merge

#908 interp: fix type check in constant unary operations
  _test/const20.go
  internal/cmd/genop/genop.go
  interp/op.go
Labels: area/core, bug, status/3-needs-merge

#910 interp: added kind to log for typecheck
  interp/typecheck.go
Labels: area/core, enhancement

#909 interp: fix assignable check
  _test/fun24.go
  _test/fun25.go
  interp/cfg.go
  interp/interp_consistent_test.go
  interp/type.go
Labels: area/core, enhancement, status/3-needs-merge

#912 interp: fix array size definition in case of forward declared constant
  _test/a44.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#913 interp: added sliceExpr and starExpr
  _test/addr1.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#915 interp: add indexExpr check for reflect.Array
  _test/slice.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#918 interp: fix type in assign of shift operations
  _test/assign16.go
  _test/select1.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#921 interp: fix type conversion for constant expressions
  _test/const21.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#923 interp: handle explicit nil values in literal composite values
  _test/composite14.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#925 interp: fix testing for nil interface values
  _test/nil3.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge
