Repository traefik/yaegi, pull requests merged in 2020-06, with the labels that each got.

#661 fix: recursive struct function call
  _test/struct47.go
  _test/struct48.go
  interp/cfg.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#668 fix: handle nil interface conversion
  _test/interface43.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#669 fix: composite literal child types for call expressions
  _test/composite10.go
  _test/composite9.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#670 fix: handle range on chan function return
  _test/range7.go
  interp/scope.go
Labels: area/core, bug, status/3-needs-merge

#676 fix: handle call ellipsis
  _test/variadic7.go
  interp/ast.go
  interp/cfg.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#673 interp: detect local redeclaration
  _test/redeclaration0.go
  _test/redeclaration1.go
  _test/redeclaration2.go
  _test/redeclaration3.go
  _test/redeclaration4.go
  _test/redeclaration5.go
  interp/cfg.go
  interp/interp_consistent_test.go
Labels: area/core, bot/need-human-merge, bug, status/3-needs-merge

#677 fix: handle printf changing nil type
  _test/recover3.go
  _test/recover4.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#674 Travis: apply timeout multiplier on CI
  .travis.yml
  cmd/yaegi/yaegi_test.go
Labels: area/infrastructure, enhancement, status/3-needs-merge

#657 fix: finish support of type assertions which was incomplete
  _test/method33.go
  _test/method34.go
  interp/gta.go
  interp/run.go
  interp/type.go
Labels: area/core, bug

#665 fix: perform send channel action for select
  _test/select12.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#678 fix: detect default comm clause in select from AST
  _test/select13.go
  interp/ast.go
  interp/cfg.go
Labels: area/core, bug

#679 fix: return correct package name for parsed package
  interp/interp.go
  interp/src.go
Labels: area/core, bug

#683 fix: composite map assign
  _test/map29.go
  interp/cfg.go
Labels: area/core, bug

#684 fix: type assertion of non-matching types
  _test/type23.go
  _test/type24.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#688 feature: refactor numeric constants and detect overflow
  _test/const13.go
  internal/genop/genop.go
  interp/ast.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/op.go
  interp/run.go
  interp/type.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#691 fix: import non-existant package
  interp/src.go
  interp/src_test.go
Labels: area/core, bug, status/3-needs-merge

#692 fix: range over channels returned by binary calls
  _test/range8.go
  interp/scope.go
Labels: area/core, bug, status/3-needs-merge

#698 interp: global scope redeclaration detection
  _test/redeclaration-global0.go
  _test/redeclaration-global1.go
  _test/redeclaration-global2.go
  _test/redeclaration-global3.go
  _test/redeclaration-global4.go
  _test/redeclaration-global5.go
  _test/redeclaration-global6.go
  interp/cfg.go
  interp/gta.go
  interp/interp_consistent_test.go
  interp/scope.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#695 fix: allow uint in make len and cap
  _test/make2.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#693 feature: unsafe type conversion
  Makefile
  _test/unsafe0.go
  _test/unsafe1.go
  _test/unsafe2.go
  _test/unsafe3.go
  _test/unsafe4.go
  cmd/yaegi/yaegi.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/interp_file_test.go
  interp/run.go
  stdlib/unsafe/unsafe.go
Labels: area/core, enhancement, status/3-needs-merge

#706 chore: update linter.
  .golangci.toml
  .travis.yml
  cmd/goexports/goexports.go
  internal/genop/genop.go
  interp/ast.go
  interp/build.go
  interp/cfg.go
  interp/dot.go
  interp/example_eval_test.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/run.go
  interp/scope.go
  interp/src.go
  interp/type.go
  stdlib/stdlib.go
  stdlib/syscall/syscall.go
  stdlib/unsafe/unsafe.go
Labels: area/infrastructure

#699 interp: force root scope for binPkgT selector
  _test/selector-scope0.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#707 fix: make reftype func variadic
  _test/variadic8.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#704 feature: add Sizeof and Alignof to unsafe
  _test/unsafe5.go
  interp/hooks.go
  interp/interp.go
  interp/run.go
  stdlib/unsafe/unsafe.go
Labels: area/stdlib, enhancement, status/3-needs-merge

#710 fix: use pragma for ptr checks
  Makefile
  stdlib/unsafe/unsafe.go
Labels: area/infrastructure, status/3-needs-merge

#702 Handle Receive and Send channels
  _test/chan10.go
  _test/range9.go
  interp/ast.go
  interp/cfg.go
  interp/interp_consistent_test.go
  interp/scope.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#708 fix: handle defer in builtins
  _test/defer5.go
  _test/defer6.go
  _test/defer7.go
  _test/defer8.go
  _test/defer9.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#715 fix: rework compatibility and ordering checks
  _test/op6.go
  _test/op7.go
  _test/op8.go
  _test/op9.go
  internal/genop/genop.go
  interp/ast.go
  interp/cfg.go
  interp/interp_consistent_test.go
  interp/interp_eval_test.go
  interp/op.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#718 fix: dont optimize map index assigns
  _test/assign13.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#723 feature: add -syscall option to enable use of syscall symbols
  cmd/yaegi/yaegi.go
Labels: area/repl, area/stdlib, enhancement

#726 feature: goexports skips unimplemented solaris Syscall6
  cmd/goexports/goexports.go
  stdlib/syscall/go1_13_syscall_solaris_amd64.go
  stdlib/syscall/go1_14_syscall_solaris_amd64.go
Labels: area/goexports, enhancement, status/3-needs-merge
