Repository traefik/yaegi, pull requests merged in 2020-07, with the labels that each got.

#717 interp: support another vendoring case
  example/pkg/_pkg10/src/github.com/foo/pkg.go
  example/pkg/_pkg10/src/github.com/foo/vendor/guthib.com/containous/fromage/fromage.go
  example/pkg/_pkg11/src/foo/foo.go
  example/pkg/_pkg11/src/foo/vendor/guthib.com/containous/fromage/fromage.go
  example/pkg/pkg_test.go
  interp/src.go
Labels: area/core, enhancement, status/3-needs-merge

#729 fix: untyped constant converson to default type
  _test/const14.go
  interp/cfg.go
  interp/run.go
  interp/scope.go
Labels: area/core, bug

#733 fix: set frame level in destination nodes to avoid memory corruption
  _test/assign14.go
  interp/cfg.go
Labels: area/core, bug, priority/P0, status/3-needs-merge

#734 feature: handle nested recursion
  _test/struct23.go
  _test/struct49.go
  _test/struct50.go
  _test/struct51.go
  _test/struct52.go
  interp/cfg.go
  interp/run.go
  interp/type.go
  interp/value.go
Labels: area/core, enhancement, status/3-needs-merge

#736 fix: switch always compare like types
  _test/switch38.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#737 fix: variadic interface conversion in call/callBin
  _test/variadic9.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#738 fix: do type check on assignment
  _test/assign15.go
  interp/cfg.go
  interp/interp_consistent_test.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#739 fix: avoid memory errors by handling frame indirections
  _test/issue-735.go
  _test/time13.go
  interp/run.go
Labels: area/core, bug

#740 fix: handle Func Value in genFunctionWrapper params
  interp/interp_eval_test.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#745 fix: a const, non-const equality check must convert
  _test/comp2.go
  internal/genop/genop.go
  interp/cfg.go
  interp/op.go
Labels: area/core, bug, status/3-needs-merge

#747 fix: assert switch type from valueT in struct case
  _test/type25.go
  _test/type26.go
  interp/cfg.go
Labels: area/core, bug

#751 fix: avoid infinite loop when parsing recursive types
  _test/struct53.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#749 fix: handle interfaces in composite sparse
  _test/interface44.go
  interp/run.go
Labels: area/core, bug

#755 fix: make a copy of defined before detecting recursivness
  _test/struct54.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#757 feature: restrict symbols which can exit the interpreter process
  _test/restricted0.go
  _test/restricted1.go
  _test/restricted2.go
  _test/restricted3.go
  cmd/goexports/goexports.go
  cmd/yaegi/yaegi.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/run.go
  stdlib/go1_13_log.go
  stdlib/go1_13_os.go
  stdlib/go1_13_os_exec.go
  stdlib/go1_14_log.go
  stdlib/go1_14_os.go
  stdlib/go1_14_os_exec.go
  stdlib/restricted.go
  stdlib/stdlib.go
  stdlib/unrestricted/unrestricted.go
Labels: area/core, area/goexports, area/stdlib, enhancement, status/3-needs-merge

#762 fix: type assert when status is _
  _test/interface45.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#764 fix: avoid a panic in CFG in case of incomplete type
  _test/const15.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#765 fix: execute global variables in the correct order
  _test/var12.go
  _test/var13.go
  _test/var14.go
  _test/vars/first.go
  _test/vars/second.go
  interp/cfg.go
  interp/gta.go
  interp/interp.go
  interp/run.go
  interp/src.go
Labels: area/core, bug, status/3-needs-merge

#767 fix: dont allow calling init
  _test/init1.go
  interp/cfg.go
  interp/gta.go
  interp/interp_consistent_test.go
Labels: area/core, bug, status/3-needs-merge

#769 fix: deal with untyped in type check
  _test/math2.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#774 fix: apply method receiver offset when generating interface wrapper
  _test/issue-772.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#777 fix: correct control flow graph for range init expression
  _test/issue-775.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#779 fix: compositeSparse handles fields of interface kind
  _test/issue-776.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#773 interp: support yet another vendoring case
  example/pkg/_pkg12/src/guthib.com/foo/main.go
  example/pkg/_pkg12/src/guthib.com/foo/pkg/pkg.go
  example/pkg/_pkg12/src/guthib.com/foo/vendor/guthib.com/bar/bar.go
  example/pkg/pkg_test.go
  interp/src.go
  interp/src_test.go
  interp/testdata/src/github.com/foo/bar/baz/baz.go
  interp/testdata/src/github.com/foo/vendor/whatever/whatever.go
Labels: area/core, bug, status/3-needs-merge

#771 fix: type assertion expression was not forwarding type
  _test/issue-770.go
  interp/cfg.go
  interp/type.go
Labels: area/core, bug

#783 fix: correct conversion to int in slice index expressions.
  _test/issue-782.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#787 fix: correct range on arrays of interface objects
  _test/issue-784.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#790 fix: regression on range following #787
  interp/cfg.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#793 chore: updated linter
  .golangci.toml
  interp/ast.go
  interp/interp_test.go
  interp/scope.go
  interp/type.go
Labels: area/infrastructure, status/3-needs-merge

#792 feat: refactor type checking
  _test/addr0.go
  _test/op1.go
  _test/rune1.go
  internal/genop/genop.go
  interp/ast.go
  interp/cfg.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/interp_eval_test.go
  interp/op.go
  interp/run.go
  interp/type.go
  interp/typecheck.go
Labels: area/core, enhancement, status/3-needs-merge
