Repository traefik/yaegi, pull requests merged in 2020-05, with the labels that each got.

#615 fix: improving handling of functions returning interfaces
  _test/fun15.go
  _test/fun16.go
  _test/fun17.go
  _test/fun18.go
  _test/map26.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#616 fix: store the result of a bin function call in frame
  _test/bin4.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#617 fix: check that a function returns the correct number of values
  _test/assign11.go
  _test/assign12.go
  interp/ast.go
  interp/cfg.go
  interp/interp_consistent_test.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#618 fix: improve switch and type switch statement processing
  _test/switch34.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#619 fix: improve generation of interface wrapper
  _test/bin5.go
  _test/fun14.go
  _test/new2.go
  _test/struct37.go
  _test/struct45.go
  _test/type22.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#620 fix: handle set of variadic arg list for a ... value
  _test/variadic6.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#621 fix: handle constant declarations inside function scopes
  _test/const11.go
  interp/cfg.go
  interp/gta.go
  interp/scope.go
Labels: area/core, bug, status/3-needs-merge

#622 feature: pre-import used packages in REPL mode.
  cmd/yaegi/yaegi.go
  cmd/yaegi/yaegi_test.go
  interp/interp.go
Labels: area/doc, area/repl, enhancement, status/3-needs-merge

#625 fix: correct assign from function returning an interface value
  _test/interface37.go
  interp/run.go
Labels: area/core, bug

#627 fix: improve setting results in multiple output functions
  _test/fun19.go
  _test/fun20.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#628 fix: assign an element in a map from runtime
  _test/map27.go
  interp/cfg.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#638 add repl input bounds check
  cmd/yaegi/yaegi.go
Labels: area/repl, bug

#632 fix: compute numeral constant on typed objects
  .travis.yml
  _test/const12.go
  interp/cfg.go
  interp/interp_test.go
Labels: area/core, bug, status/3-needs-merge

#629 fix: check the number of argument passed and returned to functions
  _test/fun21.go
  _test/fun22.go
  interp/ast.go
  interp/cfg.go
  interp/interp_consistent_test.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#644 fix: correct iterator in map range on binary values
  _test/map28.go
  interp/cfg.go
Labels: area/core, bug

#643 fix: use interface wrappers to expose interface values to runtime
  _test/interface38.go
  _test/interface39.go
  _test/interface40.go
  _test/interface41.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug

#635 fix: handle empty clause in switch if statement
  _test/switch35.go
  _test/switch36.go
  _test/switch37.go
  interp/cfg.go
Labels: area/core, bug

#650 interp: extend dot debugging
  cmd/yaegi/yaegi.go
  interp/dot.go
  interp/interp.go
  interp/src.go
Labels: area/core, enhancement, status/3-needs-merge

#653 Fix import source symbol package
  _test/baz-bat/baz-bat.go
  _test/import9.go
  interp/gta.go
  interp/src.go
Labels: area/core, bug, status/3-needs-merge

#658 fix: compose recursion
  _test/struct46.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#663 fix: nil recover case
  _test/recover2.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#664 fix: handle empty interface conversion
  _test/interface42.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge
