Repository traefik/yaegi, pull requests merged in 2020-01, with the labels that each got.

#482 fix: add support for ^ and + as unary operators
  internal/genop/genop.go
  interp/ast.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/op.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#483 doc: add explanation about CLA in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area/doc

#476 fix: use branch operation in || and && operators, fix storage for !
  _test/or0.go
  _test/or1.go
  interp/cfg.go
  interp/dot.go
  interp/run.go
Labels: area/core, bug

#477 doc: document import of source and binary packages
  interp/doc.go
  stdlib/stdlib.go
  stdlib/syscall/syscall.go
  stdlib/unsafe/unsafe.go
Labels: area/doc

#484 fix: apply automatic type conversion to constant expressions
  _test/bin2.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug

#485 fix: continue statement was not applied correctly
  _test/for8.go
  _test/primes.go
  interp/cfg.go
  interp/scope.go
Labels: area/core, bug, status/3-needs-merge

#407 Case sensitivity fix
  cmd/yaegi/yaegi.go
Labels: area/doc, status/3-needs-merge

#479 Add an example of yaegi in a shebang line
  README.md
Labels: area/doc, status/3-needs-merge
