Repository traefik/yaegi, pull requests merged in 2020-08, with the labels that each got.

#794 feature: command line provide sub-commands
  cmd/yaegi/extract.go
  cmd/yaegi/help.go
  cmd/yaegi/run.go
  cmd/yaegi/yaegi.go
Labels: area/repl, enhancement, status/3-needs-merge

#796 fix: interface call regression from #787
  _test/interface46.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#797 feat: add index and composite literal type checking
  _test/math3.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/run.go
  interp/typecheck.go
  interp/value.go
Labels: area/core, enhancement, status/3-needs-merge

#810 chore: update golangci-lint config
  .golangci.toml
  cmd/yaegi/yaegi_test.go
Labels: area/infrastructure, status/3-needs-merge

#809 interp: make REPL stricter about parsing errors
  interp/interp.go
  interp/interp_eval_test.go
Labels: area/repl, bot/need-human-merge, bug, status/3-needs-merge

#807 fix: correct interrupt signal handling in REPL
  interp/interp.go
Labels: area/repl, bug, status/3-needs-merge

#812 fix: main command for goreleaser.
  .goreleaser.yml
Labels: area/infrastructure, bug, status/3-needs-merge

#805 feat: add call expression (not builtin) type checking
  _test/a42.go
  extract/extract.go
  internal/genop/genop.go
  interp/ast.go
  interp/cfg.go
  interp/gta.go
  interp/interp_eval_test.go
  interp/op.go
  interp/type.go
  interp/typecheck.go
  interp/value.go
  stdlib/go1_14_debug_elf.go
  stdlib/go1_14_encoding_xml.go
  stdlib/go1_14_net_http.go
  stdlib/go1_14_net_http_httptest.go
  stdlib/go1_14_net_rpc.go
  stdlib/go1_14_os.go
  stdlib/go1_14_runtime.go
  stdlib/go1_14_time.go
  stdlib/go1_14_unicode.go
  stdlib/go1_15_debug_elf.go
  stdlib/go1_15_encoding_xml.go
  stdlib/go1_15_net_http.go
  stdlib/go1_15_net_http_httptest.go
  stdlib/go1_15_net_rpc.go
  stdlib/go1_15_os.go
  stdlib/go1_15_runtime.go
  stdlib/go1_15_time.go
  stdlib/go1_15_unicode.go
  stdlib/syscall/go1_14_syscall_aix_ppc64.go
  stdlib/syscall/go1_15_syscall_aix_ppc64.go
Labels: area/core, enhancement, status/3-needs-merge

#813 fix: composite literal type check
  _test/struct55.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#814 interp: more tests for ignoreScannerError
  interp/interp_eval_test.go
Labels: area/repl, area/test

#816 fix: add mutual exclusion locks for cancelable select
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#818 feat: add slice expression type checking
  interp/cfg.go
  interp/interp_eval_test.go
  interp/typecheck.go
Labels: area/core, enhancement, status/3-needs-merge

#802 interp: change API of Eval
  _test/ipp_as_key.go
  _test/pkgname0.go
  _test/pkgname1.go
  _test/pkgname2.go
  _test/redeclaration-global7.go
  _test/testdata/redeclaration-global7/src/guthib.com/bar/quux.go
  _test/testdata/redeclaration-global7/src/guthib.com/baz/quux.go
  _test/testdata/redeclaration-global7/src/guthib.com/tata/tutu.go
  _test/testdata/redeclaration-global7/src/guthib.com/toto/titi.go
  cmd/yaegi/run.go
  example/pkg/pkg_test.go
  interp/ast.go
  interp/cfg.go
  interp/export_test.go
  interp/gta.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/interp_eval_test.go
  interp/interp_file_test.go
  interp/src.go
  interp/testdata/multi/731/sample1.go
  interp/testdata/multi/731/sample2.go
  interp/testdata/multi/731/sample3.go
  interp/type.go
Labels: area/api, area/core, bug

#817 interp: take into account embedded property of struct field
  _test/struct56.go
  _test/struct57.go
  interp/type.go
Labels: area/core, bug

#821 feat: add type assertion expression type checking
  _test/method35.go
  interp/cfg.go
  interp/run.go
  interp/type.go
  interp/typecheck.go
Labels: area/core, enhancement, status/3-needs-merge

#822 feat: add star expression type checking
  interp/cfg.go
  interp/interp_eval_test.go
  interp/typecheck.go
Labels: area/core, enhancement, status/3-needs-merge

#826 fix: check array size symbol kind
  interp/interp_eval_test.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#827 feat: add builtin type checking
  interp/cfg.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/type.go
  interp/typecheck.go
Labels: area/core, enhancement, status/3-needs-merge

#823 feature: improve handling of interrupt signal in REPL
  interp/interp.go
Labels: area/repl, enhancement, status/3-needs-merge

#824 REPL: retry with full wrapping for anonymous func calls
  interp/ast.go
  interp/interp.go
  interp/interp_eval_test.go
Labels: area/repl, bug

#828 interp: enable declaration errors detection at parsing time
  _test/redeclaration-global5.go
  interp/ast.go
  interp/cfg.go
  interp/gta.go
  interp/interp_eval_test.go
Labels: area/core, enhancement

#831 TestEvalScanner: "fix" data race
  interp/interp_eval_test.go
Labels: area/test, bug, status/3-needs-merge

#830 feat: configure stdin, stdout and stderr per interpreter
  _test/eval0.go
  _test/inception.go
  cmd/yaegi/run.go
  cmd/yaegi/yaegi_test.go
  example/pkg/pkg_test.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/interp_file_test.go
  interp/run.go
Labels: area/api, area/core, area/repl, enhancement, status/3-needs-merge
