Repository traefik/yaegi, pull requests merged in 2020-09, with the labels that each got.

#839 interp: fix data races
  interp/interp.go
  interp/interp_eval_test.go
  interp/testdata/concurrent/hello1.go
  interp/testdata/concurrent/hello2.go
  interp/type.go
Labels: area/core, area/test, bug

#836 fix: correct index for embedded binary method receiver
  _test/cli6.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#833 fix: handle interface fields in literal composite structs
  _test/cli4.go
  _test/cli5.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#838 feature: test subcommand to run test and benchmark functions
  _test/m1/main.go
  _test/m1/main_test.go
  cmd/goexports/goexports.go
  cmd/yaegi/extract.go
  cmd/yaegi/help.go
  cmd/yaegi/run.go
  cmd/yaegi/test.go
  cmd/yaegi/yaegi.go
  interp/build.go
  interp/build_test.go
  interp/dot.go
  interp/gta.go
  interp/interp.go
  interp/src.go
  stdlib/go1_14_testing.go
  stdlib/go1_14_testing_iotest.go
  stdlib/go1_14_testing_quick.go
  stdlib/go1_15_testing.go
  stdlib/go1_15_testing_iotest.go
  stdlib/go1_15_testing_quick.go
  stdlib/stdlib.go
Labels: area/api, area/core, area/stdlib, enhancement, status/3-needs-merge

#846 fix: keep atomic counter aligned on 64 bits boundary
  interp/interp.go
Labels: arch/32bits, area/core, bug, status/3-needs-merge

#849 interp: fix data race for composite literal creation
  interp/interp_eval_test.go
  interp/run.go
  interp/testdata/concurrent/composite/composite_lit.go
  interp/testdata/concurrent/composite/composite_sparse.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#844 fix: native build of syscalls on android and illumos
  extract/extract.go
  interp/build.go
  stdlib/syscall/go1_14_syscall_android_386.go
  stdlib/syscall/go1_14_syscall_android_amd64.go
  stdlib/syscall/go1_14_syscall_android_arm.go
  stdlib/syscall/go1_14_syscall_android_arm64.go
  stdlib/syscall/go1_14_syscall_illumos_amd64.go
  stdlib/syscall/go1_15_syscall_android_386.go
  stdlib/syscall/go1_15_syscall_android_amd64.go
  stdlib/syscall/go1_15_syscall_android_arm.go
  stdlib/syscall/go1_15_syscall_android_arm64.go
  stdlib/syscall/go1_15_syscall_illumos_amd64.go
Labels: area/goexports, area/stdlib, bug, os/android, status/3-needs-merge

#855 chore: adds a downloader script.
  Makefile
  README.md
  install.sh
Labels: area/infrastructure, enhancement, status/3-needs-merge

#859 fix: correct access to parameter type for variadic binary methods
  _test/m2/m2_test.go
  _test/variadic10.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#861 interp: refactor doComposite cases
  _test/composite12.go
  _test/composite13.go
  _test/composite8bis.go
  interp/cfg.go
  interp/interp.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#863 interp: fix division for const
  _test/const16.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#869 fix: yaegi os.Args should contain the script name
  cmd/yaegi/run.go
Labels: area/repl, area/stdlib, bug, status/3-needs-merge

#874 fix: convert struct tags properly
  _test/struct58.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#872 fix: concurrent eval test
  interp/interp_eval_test.go
Labels: area/test, bug, status/3-needs-merge

#877 fix: replace playground link in docs
  README.md
Labels: area/doc, bug, status/3-needs-merge
