Repository traefik/yaegi, pull requests merged in 2020-11, with the labels that each got.

#931 interp: on panic, look for node where offending exec originated from
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#934 interp: fix incorrect infinite loop on for statement
  _test/for15.go
  interp/ast.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#930 interp: resolve type for untyped shift expressions
  interp/cfg.go
  interp/interp_eval_test.go
  interp/run.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#937 interp: implement conversion for interpreter function types
  _test/convert0.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#940 interp: apply type conversion on untyped variable at run
  interp/interp_eval_test.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#945 interp: fix CFG in case of for loop with empty init and cond
  _test/for16.go
  interp/ast.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#944 fix: use the import path for types
  example/pkg/_pkg13/src/guthib.com/foo/bar/main.go
  example/pkg/_pkg13/src/guthib.com/foo/bar/vendor/guthib.com/bat/baz/baz.go
  example/pkg/pkg_test.go
  interp/gta.go
Labels: area/core, bug, status/3-needs-merge

#949 interp: fix getting unsigned constant value
  interp/interp_eval_test.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#946 interp: support conversion of runtime func into interp func
  _test/convert1.go
  _test/convert2.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#954 interp: avoid useless interface wrapping
  interp/run.go
Labels: area/core, enhancement, status/3-needs-merge

#958 interp: fix type check on function signature
  _test/time14.go
  interp/cfg.go
  interp/scope.go
Labels: area/core, bug, status/3-needs-merge

#962 fix: do not confuse function call with type conversion
  _test/fun26.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#956 interp: support calling goto from sub-scope
  _test/goto1.go
  interp/cfg.go
  interp/scope.go
Labels: area/core, bug, status/3-needs-merge

#965 test: chdir to package directory prior to launch tests
  cmd/yaegi/test.go
Labels: area/cli, area/test, enhancement, status/3-needs-merge

#964 interp: handle getting address of interpreter interface value
  _test/addr2.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#972 interp: fix method lookup on aliased types
  _test/time15.go
  interp/cfg.go
  interp/gta.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#970 interp: fix parsing of assign to dereferenced pointer
  interp/cfg.go
  interp/interp_eval_test.go
Labels: area/core, bug, status/3-needs-merge

#966 interp: support more type assertion cases
  _test/assert0.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge
