Repository traefik/yaegi, pull requests merged in 2021-08, with the labels that each got.

#1210 interp: fix package lookup for type analysis of local types
  interp/gta.go
Labels: area/core, bug, status/3-needs-merge

#1209 interp: improve handling of interface struct field
  _test/issue-1208.go
  interp/run.go
Labels: bug, status/3-needs-merge, area/core

#1216 feat: fix zero instance issue
  _test/struct60.go
  interp/run.go
Labels: bug, status/3-needs-merge, area/core

#1217 interp: fix handling of forward function declaration
  _test/fun27.go
  interp/ast.go
Labels: bug, status/3-needs-merge, area/core

#1222 stdlib: remove wrapper of runtime/cgo
  stdlib/go1_17_runtime_cgo.go
  stdlib/stdlib_go1.17.go
Labels: bug, status/3-needs-merge, area/stdlib

#1220 stdlib: support go1.17 unsafe functions
  _test/unsafe6.go
  _test/unsafe7.go
  interp/interp_consistent_test.go
  stdlib/unsafe/unsafe_go1.17.go
Labels: enhancement, status/3-needs-merge, area/stdlib

#1199 interp: allow for reading source files from diverse filesystems
  example/fs/fs_test.go
  go.mod
  interp/interp.go
  interp/realfs.go
  interp/src.go
  interp/src_test.go
Labels: enhancement, status/3-needs-merge, area/core, area/api

#1226 interp: fix append with 1 argument
  interp/interp_eval_test.go
  interp/run.go
  interp/typecheck.go
Labels: bug, status/3-needs-merge, area/core

#1236 interp: create real recursive types with unsafe type swapping
  internal/unsafe2/unsafe.go
  internal/unsafe2/unsafe_test.go
  interp/run.go
  interp/type.go
  interp/typecheck.go
  interp/value.go
Labels: status/3-needs-merge, area/core

#1237 interp: make use of type constructors
  interp/gta.go
  interp/interp.go
  interp/src.go
  interp/type.go
Labels: enhancement, status/3-needs-merge, area/core

#1240 interp: fix default types for runes
  _test/rune2.go
  interp/type.go
Labels: bug, status/3-needs-merge, area/core
