Repository traefik/yaegi, pull requests merged in 2021-02, with the labels that each got.

#1023 chore: use GitHub Actions.
  .github/workflows/go-cross.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .golangci.toml
  .travis.yml
  cmd/yaegi/extract.go
  cmd/yaegi/yaegi_test.go
  example/pkg/pkg_test.go
  extract/extract.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/interp_export_test.go
  interp/interp_file_test.go
  interp/run.go
Labels: area/infrastructure, enhancement, status/2-needs-review

#1027 interp: clarify error about GOPATH probably not set
  interp/src.go
  interp/src_test.go
Labels: area/core, bug, status/3-needs-merge

#1028 interp: fix nil value check in case of interface
  _test/issue-1022.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1029 interp: fix default type for constants from runtime
  _test/time16.go
  interp/type.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#1017 interp: do not wrap empty interface
  _test/add1.go
  _test/addr2.go
  _test/addr3.go
  _test/addr4.go
  _test/addr5.go
  _test/assert0.go
  _test/assert1.go
  _test/cap0.go
  _test/composite15.go
  _test/fun15.go
  _test/fun16.go
  _test/method34.go
  _test/switch34.go
  internal/cmd/genop/genop.go
  interp/cfg.go
  interp/interp_eval_test.go
  interp/op.go
  interp/run.go
  interp/type.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#1032 interp: fix setting interface objects from operators
  _test/interface50.go
  internal/cmd/genop/genop.go
  interp/op.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1034 fix: use portable path manipulation for choosing package names
  cmd/yaegi/extract.go
Labels: bug, os/windows, status/3-needs-merge

#1039 Use fmt.Fprintln instead of fmt.Println in runCfg
  interp/interp.go
  interp/run.go
Labels: area/core, enhancement, status/3-needs-merge
