Repository traefik/yaegi, pull requests merged in 2021-06, with the labels that each got.

#1131 interp: fix use of unrestricted symbols
  stdlib/unrestricted/unrestricted.go
Labels: area/core, bug, status/3-needs-merge

#1135 interp: avoid panic in output value generation for recursive types
  _test/issue-1134.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#1137 interp: fix detection of binary types implementing interfaces
  _test/issue-1136.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1127 interp: fix a wrong control flow in switch
  _test/addr2.go
  _test/addr4.go
  _test/issue-1094.go
  _test/issue-1126.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#1140 interp: handle binary array literals
  interp/cfg.go
Labels: area/core, enhancement, status/3-needs-merge

#1130 interp: fix append a slice on binary slice
  _test/append3.go
  _test/issue-1128.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1143 Add a newline after src in wrapInMain
  interp/ast.go
  interp/interp_eval_test.go
Labels: area/core, bug, status/3-needs-merge

#1155 Avoid unnecessary calls to FieldByIndex
  interp/interp_eval_test.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1153 Correctly resolve type aliases when building array literals
  interp/interp_eval_test.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1141 interp: preserve concrete type when converting type to interface
  _test/issue-1136.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#1148 interp: fix handing nil when appending to a slice
  _test/append4.go
  interp/type.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#1146 interp: fix assign of function values with binary methods
  _test/issue-1145.go
  interp/cfg.go
  interp/type.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#1152 Fix handling of ImportUsed packages
  interp/cfg.go
  interp/interp_eval_test.go
Labels: area/core, bug, status/3-needs-merge

#1162 Update Interpreter.Use API
  cmd/yaegi/run.go
  cmd/yaegi/test.go
  example/closure/closure_test.go
  example/getfunc/getfunc_test.go
  example/pkg/pkg_test.go
  interp/interp.go
  interp/interp_consistent_test.go
  interp/interp_eval_test.go
  interp/interp_export_test.go
  interp/interp_file_test.go
  interp/self_example_test.go
Labels: area/api, bug, status/3-needs-merge

#1161 interp: improve handling of interface values
  _test/issue-1156.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge
