Repository traefik/yaegi, pull requests merged in 2021-03, with the labels that each got.

#1044 interp: fix a memory management issue causing wrong closure context
  _test/closure10.go
  _test/closure11.go
  _test/closure12.go
  _test/closure9.go
  _test/select14.go
  cmd/yaegi/yaegi_test.go
  interp/cfg.go
  interp/interp.go
  interp/interp_eval_test.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1048 interp: do not check properties of incomplete types
  _test/const25.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#1050 interp: fix closure in a struct field
  _test/method36.go
  interp/cfg.go
  interp/run.go
  interp/type.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#1054 interp: do not skip use of tmp frame in multi-assign
  _test/issue-1052.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#1057 fix #1056, extract: replace the code for get package name.
  extract/extract.go
  extract/extract_test.go
  extract/testdata/6/src/guthib.com/bar/main.go
  extract/testdata/6/src/guthib.com/baz-baz/baz.go
  extract/testdata/6/src/guthib.com/baz-baz/go.mod
Labels: area/extract, bug, status/3-needs-merge

#1061 extract: process interface wrapper method with variadic parameter
  extract/extract.go
  extract/extract_test.go
  extract/testdata/7/src/guthib.com/variadic/go.mod
  extract/testdata/7/src/guthib.com/variadic/variadic.go
  stdlib/go1_15_testing.go
  stdlib/go1_16_testing.go
Labels: area/extract, bug, status/3-needs-merge

#1066 interp: allow redeclaration of imports
  interp/gta.go
Labels: area/core, enhancement, status/3-needs-merge

#1067 interp: fix append on variadic recursive struct
  _test/issue-1065.go
  interp/run.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge
