Repository traefik/yaegi, pull requests merged in 2021-07, with the labels that each got.

#1165 chore: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
Labels: area/infrastructure, enhancement, status/3-needs-merge

#1169 Update README.md
  README.md
Labels: area/doc, status/3-needs-merge

#1164 interp: improve field and method resolution in presence of collisions.
  _test/issue-1163.go
  interp/cfg.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1174 interp: fix the detection of builtin calls during parsing
  _test/issue-1173.go
  interp/cfg.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1176 interp: fix array declaration with a typed constant size
  _test/issue-1175.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1178 interp: fix type checking of address of multi dimension array
  _test/issue-1177.go
  interp/typecheck.go
Labels: area/core, bug, status/3-needs-merge

#1180 interp: fix handling of interface value in forwarding return calls
  _test/issue-1179.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1168 interp: fix method resolution on pointer to binary values
  _test/issue-1167.go
  interp/cfg.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1184 interp: fix swap assign with extra operation
  _test/issue-1181.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#1183 interp: fix receiver for exported method objects
  _test/d1/d1.go
  _test/d2/d2.go
  _test/d3.go
  interp/cfg.go
Labels: area/core, bug, status/3-needs-merge

#1186 interp: fix append of values to an array of interface objects
  _test/issue-1185.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1190 chore: update linter
  .github/workflows/go-cross.yml
  .github/workflows/main.yml
  .golangci.toml
  interp/typecheck.go
Labels: area/infrastructure, status/3-needs-merge

#1192 interp: fix interface wrapper generation
  _test/interface52.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1197 interp: fix map update by assign operators
  internal/cmd/genop/genop.go
  interp/interp_eval_test.go
  interp/op.go
Labels: area/core, bug, status/3-needs-merge

#1198 interp: fix handling map of interfaces
  _test/issue-1189.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1204 interp: fix handling returned func values
  _test/issue-1202.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge

#1193 interp: support wrapping of nested interfaces
  _test/issue-1128.go
  _test/issue-1187.go
  interp/cfg.go
  interp/interp.go
  interp/run.go
  interp/value.go
Labels: area/core, bug, status/3-needs-merge

#1201 stdlib: add missing wrappers of io/fs for go1.16
  interp/interp_eval_test.go
  stdlib/go1_16_io_fs.go
  stdlib/stdlib_go1.16.go
Labels: area/stdlib, bug, status/3-needs-merge

#1207 interp: fix handling of interface values in variadic calls
  _test/issue-1205.go
  interp/run.go
Labels: area/core, bug, status/3-needs-merge
