Repository traefik/yaegi, pull requests merged in 2021-04, with the labels that each got.

#1064 interp: fix a panic when embedding an error interface
  _test/interface51.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1072 interp: treat var declaration within a block as a define statement
  .github/workflows/go-cross.yml
  interp/ast.go
  interp/cfg.go
  interp/interp_eval_test.go
Labels: area/core, bug, status/3-needs-merge

#1073 chore: restore macos env in GitHub Actions.
  .github/workflows/go-cross.yml
Labels: area/infrastructure, bug, status/3-needs-merge

#1070 Allow colon-equal to override variable type
  interp/gta.go
  interp/interp_eval_test.go
Labels: area/core, enhancement, status/3-needs-merge

#1074 interp: refactor slice type management
  interp/cfg.go
  interp/run.go
  interp/type.go
  interp/typecheck.go
Labels: area/core, enhancement, status/3-needs-merge

#1076 interp: fix method lookup for aliased types
  interp/cfg.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1080 interp: implement unsafe.Offsetof
  _test/unsafe5.go
  interp/cfg.go
  stdlib/unsafe/unsafe.go
Labels: area/core, area/stdlib, enhancement, status/3-needs-merge

#1075 interp: improve handling of aliased types
  _test/issue-1068.go
  interp/cfg.go
  interp/run.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1086 stdlib: add wrapper for testing/fstest package in go1.16
  stdlib/go1_16_testing_fstest.go
  stdlib/stdlib_go1.16.go
Labels: area/stdlib, enhancement, status/3-needs-merge

#1087 interp: give a self to the interpreter
  interp/interp.go
Labels: area/api, enhancement, status/3-needs-merge

#1096 interp: fix type string extraction for wrapped constants
  _test/issue-1089.go
  interp/type.go
Labels: area/core, bug, status/3-needs-merge

#1085 interp: add ImportUsed method to pre-import compiled packages
  cmd/yaegi/run.go
  interp/gta.go
  interp/interp.go
  interp/typecheck.go
Labels: area/api, area/cli, bug, status/3-needs-merge
