Repository traefik/yaegi, pull requests merged in 2021-09, with the labels that each got.

#1241 interp: complete type constructors
  _test/alias2.go
  interp/cfg.go
  interp/gta.go
  interp/interp.go
  interp/scope.go
  interp/src.go
  interp/type.go
  interp/typestring.go
Labels: enhancement, status/3-needs-merge, area/core

#1225 interp: add debug interface
  interp/ast.go
  interp/cfg.go
  interp/debugger.go
  interp/interp.go
  interp/program.go
  interp/run.go
  interp/type.go
Labels: enhancement, status/3-needs-merge, area/core, area/api

#1242 interp: improve handling of wrapped interface values
  _test/assert2.go
  interp/run.go
  interp/value.go
Labels: bug, status/3-needs-merge, area/core

#1243 interp: fix parsing of late binding consts
  _test/const26.go
  interp/gta.go
Labels: bug, status/3-needs-merge, area/core

#1244 interp: types should not recover data for aliases
  _test/alias3.go
  _test/alias3/alias3.go
  interp/gta.go
  interp/type.go
Labels: bug, status/3-needs-merge, area/core

#1250 interp: fix nil funcs in composite literals
  _test/composite18.go
  _test/composite19.go
  interp/value.go
Labels: bug, status/3-needs-merge, area/core

#1246 interp: improve processing of recursive types
  interp/cfg.go
  interp/gta.go
  interp/type.go
  interp/typecheck.go
Labels: bug, status/3-needs-merge, area/core

#1252 interp: fix Clone documentation
  interp/type.go
Labels: area/doc, status/3-needs-merge

#1248 interp: fix type selector precedence
  _test/alias3.go
  _test/alias3/alias3.go
  _test/selector-scope0.go
  interp/type.go
Labels: bug, status/3-needs-merge, area/core

#1247 interp: do not export RealFS, used internally only
  interp/interp.go
  interp/realfs.go
  interp/src_test.go
Labels: status/3-needs-merge, area/api

#1256 chore: update linter to v1.42.1
  .github/workflows/main.yml
  .golangci.toml
  internal/cmd/genop/genop.go
  interp/interp_consistent_test.go
  interp/src_test.go
  stdlib/stdlib.go
  stdlib/syscall/syscall.go
  stdlib/unsafe/unsafe.go
Labels: enhancement, status/3-needs-merge, area/infrastructure

#1254 interp: allow GTA revisit for unresolved define statements
  _test/method38.go
  _test/method38/a.go
  _test/method38/b.go
  _test/method39.go
  interp/gta.go
  interp/interp.go
  interp/interp_consistent_test.go
Labels: bug, status/3-needs-merge, area/core

#1257 interp: support type spec assign
  _test/type27.go
  _test/type28.go
  _test/type29.go
  _test/type30.go
  _test/type31.go
  _test/type32.go
  _test/type33.go
  interp/ast.go
  interp/gta.go
  interp/interp_consistent_test.go
Labels: bug, status/3-needs-merge, area/core

#1261 interp: add a function to directly compile Go AST
  interp/ast.go
  interp/compile_test.go
  interp/interp.go
  interp/program.go
  interp/src.go
Labels: enhancement, status/3-needs-merge, area/api

#1258 interp: fix interface wrapper for struct types
  interp/run.go
Labels: bug, status/3-needs-merge, area/core

#1263 interp: handle alias of an alias
  _test/alias4.go
  interp/cfg.go
  interp/type.go
Labels: bug, status/3-needs-merge, area/core

#1264 interp: handle recursive and incomplete seen types in nodeType
  interp/type.go
Labels: status/3-needs-merge, area/core
