Repository traefik/yaegi, pull requests merged in 2022-04, with the labels that each got.

#1336 interp: make methods passed as value preserve receiver
  _test/issue-1332.go
  interp/run.go
Labels: bug, status/3-needs-merge, area/core

#1362 interp: fix passing binary function as parameter
  _test/issue-1361.go
  interp/run.go
  interp/value.go
Labels: bug, status/3-needs-merge, area/core

#1366 interp: fix interface conversion from binary call
  _test/issue-1364.go
  interp/value.go
Labels: bug, area/core

#1367 interp: fix handling of redeclaration in multi-assign expression
  _test/issue-1365.go
  _test/var16.go
  interp/cfg.go
Labels: bug, area/core

#1370 interp: fix switch expression
  _test/issue-1368.go
  interp/cfg.go
Labels: bug, area/core

#1376 Prevent variadic arguments from being wrapped as function
  _test/issue-1375.go
  interp/run.go
Labels: bug, status/3-needs-merge, area/core

#1372 interp: handle struct with multiple recursive fields
  _test/issue-1371.go
  interp/type.go
Labels: bug, area/core

#1374 Ignore private methods for binary types during type assertion
  _test/issue-1373.go
  interp/typecheck.go
Labels: bug, status/3-needs-merge, area/core

#1379 interp: fix redeclaration scope issue
  _test/issue-1378.go
  interp/cfg.go
Labels: bug, status/3-needs-merge, area/core

#1384 interp: expose fset to fix CompileAST issue
  interp/compile_test.go
  interp/interp_eval_test.go
  interp/program.go
Labels: enhancement, status/3-needs-merge, area/core, area/api

#1387 interp: add a function to get globals
  interp/interp_test.go
  interp/scope.go
Labels: enhancement, area/core, area/api

#1389 interp: delete incomplete type on pkg import
  interp/gta.go
  interp/interp_eval_test.go
Labels: bug, status/3-needs-merge, area/core, bot/need-human-merge
